version: "3.8"

services:
  web:
    build: .
    container_name: python_app_web
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: development
      SECRET_KEY: "your-secret-key"
      DEV_DATABASE_URL: "sqlite:////data/data-dev.sqlite"
    volumes:
      - .:/app
      - app_data:/data
    command: gunicorn --certfile fullchain.pem --keyfile privkey.pem wsgi:app --log-file - --bind 0.0.0.0:8000


volumes:
  app_data:
