"""empty message

Revision ID: 4afaa2859dc6
Revises: 
Create Date: 2020-11-20 21:24:34.433551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4afaa2859dc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('drafted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('drafted_person_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('was_drafted', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['drafted_person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'was_drafted')
    op.drop_column('users', 'drafted_person_id')
    op.drop_column('users', 'drafted')
    # ### end Alembic commands ###
